name: Deploy to Minikube

on:
  push:
    branches:
      - main   # ya tumhara default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t awsconfig-app:latest .

      # 4. Copy Kubernetes manifests
      - name: Copy Kubernetes manifests
        run: |
          cp -r Kubernetes ./k8s-temp

      # 5. Setup Minikube (using kind as Minikube alternative)
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.0
        with:
          minikube-version: 'latest'
          driver: docker

      # 6. Point Docker to Minikube
      - name: Use Minikube Docker daemon
        run: |
          eval $(minikube docker-env)

      # 7. Rebuild image in Minikube Docker
      - name: Build Docker image in Minikube
        run: |
          docker build -t awsconfig-app:latest .

      # 8. Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f Kubernetes/

      # 9. Check pods status
      - name: Get pods
        run: |
          kubectl get pods -n zomato
